- name: Deploy Tomcat to Kubernetes server
  hosts: Docker-Host
  become: false

  tasks:
    - name: Copy deployment file to Kubernetes server
      copy:
        src: /var/lib/jenkins/workspace/Dev/tomcat-app.yml
        dest: /home/ec2-user/tomcat-app.yml

    - name: Apply Kubernetes deployment
      command: kubectl apply -f /home/ec2-user/tomcat-app.yml
