- name: Deploy Tomcat to Kubernetes server
  hosts: kubernetes
  become: false

  tasks:
    - name: Copy deployment file to Kubernetes server
      copy:
        src: tomcat-app.yml
        dest: /home/ec2-user/tomcat-app.yml

    - name: Apply Kubernetes deployment
      command: kubectl apply -f /home/ec2-user/tomcat-app.yml
